/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database4object.Controllers;

/**
 *
 * @author jairo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        super.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanePrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonNuevoLibro = new javax.swing.JButton();
        jButtonModificarLibro = new javax.swing.JButton();
        jButtonMostrarTematicas = new javax.swing.JButton();
        jButtonNuevaTematica = new javax.swing.JButton();
        jButtonModificarTematica = new javax.swing.JButton();
        jButtonMostrarLibros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanePrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Biblioteca");

        jButtonNuevoLibro.setText("Nuevo libro");
        jButtonNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoLibroActionPerformed(evt);
            }
        });

        jButtonModificarLibro.setText("Modificar libros");
        jButtonModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarLibroActionPerformed(evt);
            }
        });

        jButtonMostrarTematicas.setText("Mostrar tematicas");
        jButtonMostrarTematicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarTematicasActionPerformed(evt);
            }
        });

        jButtonNuevaTematica.setText("Nueva tematica");
        jButtonNuevaTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaTematicaActionPerformed(evt);
            }
        });

        jButtonModificarTematica.setText("Modificar tematica");
        jButtonModificarTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTematicaActionPerformed(evt);
            }
        });

        jButtonMostrarLibros.setText("Mostrar libros");
        jButtonMostrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanePrincipalLayout = new javax.swing.GroupLayout(jPanePrincipal);
        jPanePrincipal.setLayout(jPanePrincipalLayout);
        jPanePrincipalLayout.setHorizontalGroup(
            jPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanePrincipalLayout.createSequentialGroup()
                .addGroup(jPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanePrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanePrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMostrarLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMostrarTematicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNuevaTematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNuevoLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModificarTematica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModificarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanePrincipalLayout.setVerticalGroup(
            jPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(123, 123, 123)
                .addGroup(jPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostrarLibros)
                    .addComponent(jButtonModificarLibro)
                    .addComponent(jButtonNuevoLibro))
                .addGap(25, 25, 25)
                .addGroup(jPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostrarTematicas)
                    .addComponent(jButtonNuevaTematica)
                    .addComponent(jButtonModificarTematica))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarLibrosActionPerformed
        // TODO add your handling code here:
        MostrarLibrosController mostrarLibros = new MostrarLibrosController();
        mostrarLibros.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jButtonMostrarLibrosActionPerformed

    private void jButtonNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoLibroActionPerformed
        // TODO add your handling code here:
        NuevoLibroController nuevoLibro = new NuevoLibroController();
        nuevoLibro.setVisible(true);
         super.dispose();
    }//GEN-LAST:event_jButtonNuevoLibroActionPerformed

    private void jButtonModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarLibroActionPerformed
        // TODO add your handling code here:
        ModificarLibroController modificarLibro = new ModificarLibroController();
        modificarLibro.setVisible(true);
         super.dispose();
    }//GEN-LAST:event_jButtonModificarLibroActionPerformed

    private void jButtonMostrarTematicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarTematicasActionPerformed
        // TODO add your handling code here:
        MostrarTematicasController mostrarTematica = new MostrarTematicasController();
        mostrarTematica.setVisible(true);
         super.dispose();
    }//GEN-LAST:event_jButtonMostrarTematicasActionPerformed

    private void jButtonNuevaTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaTematicaActionPerformed
        // TODO add your handling code here:
        NuevaTematicaController nuevaTematica = new NuevaTematicaController();
        nuevaTematica.setVisible(true);
         super.dispose();
    }//GEN-LAST:event_jButtonNuevaTematicaActionPerformed

    private void jButtonModificarTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTematicaActionPerformed
        // TODO add your handling code here:
        ModificarTematica modificarTematica = new ModificarTematica();
        modificarTematica.setVisible(true);
         super.dispose();
    }//GEN-LAST:event_jButtonModificarTematicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarLibro;
    private javax.swing.JButton jButtonModificarTematica;
    private javax.swing.JButton jButtonMostrarLibros;
    private javax.swing.JButton jButtonMostrarTematicas;
    private javax.swing.JButton jButtonNuevaTematica;
    private javax.swing.JButton jButtonNuevoLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanePrincipal;
    // End of variables declaration//GEN-END:variables
}
