/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database4object.Controllers;

import database4object.Recursos.Translations.Translations_ES;
import database4object.Services.TematicaServices;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author jairo
 */
public class ModificarTematicaController extends javax.swing.JFrame {

    TematicaServices tematicaServices;

    /**
     * Creates new form ModificarTematica
     */
    public ModificarTematicaController() {
        initComponents();
        super.setResizable(false);
        tematicaServices = new TematicaServices();
        jLabelInformacion.setVisible(false);
        jLabelErrorNoExisteTematica.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFielNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonCrearTematica = new javax.swing.JButton();
        jTextFieldNuevoNombre = new javax.swing.JTextField();
        jLabelInformacion = new javax.swing.JLabel();
        jLabelErrorNoExisteTematica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Biblioteca | Modificación temática");

        jTextFielNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFielNombre.setText("Nombre");
        jTextFielNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFielNombreMouseClicked(evt);
            }
        });
        jTextFielNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielNombreActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonCrearTematica.setText("Modificar");
        jButtonCrearTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTematicaActionPerformed(evt);
            }
        });

        jTextFieldNuevoNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNuevoNombre.setText("Nuevo nombre");
        jTextFieldNuevoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNuevoNombreMouseClicked(evt);
            }
        });
        jTextFieldNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNuevoNombreActionPerformed(evt);
            }
        });

        jLabelInformacion.setBackground(new java.awt.Color(204, 204, 204));
        jLabelInformacion.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorNoExisteTematica.setBackground(new java.awt.Color(204, 204, 204));
        jLabelErrorNoExisteTematica.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCrearTematica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabelInformacion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNuevoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFielNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErrorNoExisteTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorNoExisteTematica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonCrearTematica))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        super.dispose();
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNuevoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNuevoNombreActionPerformed

    private void jButtonCrearTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTematicaActionPerformed
        // TODO add your handling code here:
        TematicaServices tematicaservices = new TematicaServices();
        String nombreAntiguo = jTextFielNombre.getText().toLowerCase();
        String nuevoNombre = jTextFieldNuevoNombre.getText().toLowerCase();
        System.out.println(tematicaservices.existeTematica(nombreAntiguo));
        if(primeraDatoEsCorrecto(nombreAntiguo) && segundoDatoEsCorrecto(nuevoNombre)){
            if(tematicaservices.existeTematica(nombreAntiguo)){
                tematicaservices.modificarTematica(nombreAntiguo, nuevoNombre);
                 jLabelInformacion.setText(Translations_ES.OPERACION_REALIZADA_CON_EXITO);
                jLabelInformacion.setForeground(Color.BLACK);
                jLabelInformacion.setVisible(true);
            }else {
                jLabelErrorNoExisteTematica.setText(Translations_ES.TEMATICA_NO_ENCONTRADA);
                jLabelErrorNoExisteTematica.setVisible(true);
            }
        
        }else{
            jLabelInformacion.setText(Translations_ES.ES_NECESARIO_RELLENAR_TODOS_LOS_CAMPOS);
            jLabelInformacion.setVisible(true);
        }

    }//GEN-LAST:event_jButtonCrearTematicaActionPerformed

    private void jTextFielNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFielNombreMouseClicked
        // TODO add your handling code here:
        jTextFielNombre.setText("");
        jLabelErrorNoExisteTematica.setVisible(false);
    }//GEN-LAST:event_jTextFielNombreMouseClicked

    private void jTextFieldNuevoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNuevoNombreMouseClicked
        // TODO add your handling code here:
        jTextFieldNuevoNombre.setText("");
    }//GEN-LAST:event_jTextFieldNuevoNombreMouseClicked

     public boolean segundoDatoEsCorrecto(String nombreNuevo){
        boolean respuesta = true;
        if(nombreNuevo.length()<1 || nombreNuevo.equalsIgnoreCase(Translations_ES.NUEVO_NOMBRE)){
            System.out.println("segundo dato no es correcto");
        respuesta = false;
        }
        return respuesta;
    }
    public boolean primeraDatoEsCorrecto(String nombre){
        boolean respuesta = true;
        if(nombre.length()<1 || nombre.equalsIgnoreCase(Translations_ES.NOMBRE)){
            System.out.println("Primer dato no es correcto");
        respuesta = false;
        }
        return respuesta;
    }

    /**
     *
     * @param nombreAntiguo
     * @param nombreNuevo
     * @return respuesta boolean , si los datos introducidos estan vacios o
     * tienen los caracteres por defecto devuelve true, impidiendo que se creen
     * tematicas con estas caracteristicas.
     */


    public boolean comprobarTematica(String nombreAntigua, String nuevoNombre) {
        boolean respuesta = false;
        if (nombreAntigua.equals(nuevoNombre)) {
            respuesta = true;
        }
        return respuesta;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTematicaController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTematicaController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTematicaController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTematicaController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTematicaController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCrearTematica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelErrorNoExisteTematica;
    private javax.swing.JLabel jLabelInformacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFielNombre;
    private javax.swing.JTextField jTextFieldNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
